### ISSUE TITLE
[Question] Project discontinued

### ISSUE THREAD

**Issue by anjosanap** [grafana/xk6-amqp#7]
Has this project been discontinued?

**Comment by na--** [comment]
It's not discontinued, no. However, as it says on the top of the [README](https://github.com/grafana/xk6-amqp#readme), it has always been a proof of concept extension that is not very actively maintained either... :disappointed: 

This repo and other similar PoC extensions were created before k6 had support for event loops, so we couldn't nicely add support for messaging protocols like this one either in the k6 core or even in a polished extension. We've since added basic support for event loops in [k6 v0.37.0](https://github.com/grafana/k6/releases/tag/v0.37.0) and we're slowly continuing to build on top of it (e.g. https://github.com/grafana/k6/issues/2544). We'll probably pick prioritize picking up on extensions like this one in the relatively near future, though I have no idea exactly which ones and what the priorities will be :man_shrugging: 

Even if we don't work on this ourselves, it can still be somewhat usable as it is or it can be forked and improved upon. I see there are already [a few forks of the repo](https://github.com/grafana/xk6-amqp/network/members), and we'll probably accept quality PRs to merge changes back here :slightly_smiling_face:
